language: objective-c
sudo: false
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
matrix:
  include:
    - osx_image: xcode9.3
      env: RFCI_TASK="POD_LINT"
    - osx_image: xcode9.3
      env: RFCI_TASK="Xcode9"
    - osx_image: xcode8.3
      env: RFCI_TASK="Xcode8"
before_install:
  - pod repo update master --silent
script: ./.travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
