language: objective-c
osx_image: xcode9.2
sudo: false
cache: cocoapods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
# podfile: Example/Podfile
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod repo update master 
- pod install
script:
- set -o pipefail
- xcodebuild test -enableCodeCoverage YES -workspace UnitTest/RFKit.xcworkspace -scheme Test-iOS -destination "$XB_DEST" ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild test -enableCodeCoverage YES -workspace UnitTest/RFKit.xcworkspace -scheme Test-macOS ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild test -enableCodeCoverage YES -workspace UnitTest/RFKit.xcworkspace -scheme Test-tvOS -destination "platform=tvOS Simulator,name=Apple TV,OS=11.3" ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild build -workspace UnitTest/RFKit.xcworkspace -scheme Target-watchOS ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
after_failure:
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
