
target 'Test-iOS' do
    platform :ios, '7.0'

    pod 'RFKit', :path => '..', :subspecs => ['ALL']
end

target 'Test-macOS' do
    platform :osx, '10.8'
    
    pod 'RFKit', :path => '..', :subspecs => ['ALL']
end

target 'Test-tvOS' do
    platform :tvos, '9.0'
    
    pod 'RFKit', :path => '..', :subspecs => ['ALL']
end

target 'Target-watchOS' do
    platform :watchos, '2.0'
    
    pod 'RFKit', :path => '..', :subspecs => ['ALL']
end
